name: Create Release and Upload Binaries

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.3

    - name: Get dependencies
      run: go get -v -t -d ./...
      env:
        GO111MODULE: "auto"

    - name: Build
      run: go build -ldflags "-X main.GitCommit=$(git rev-parse --short HEAD)"

    - name: Upload built binary
      uses: actions/upload-artifact@v2
      with:
        name: AppleTVRestarter-${{ matrix.os }}
        path: ./AppleTVRestarter

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download all artifacts
      uses: actions/download-artifact@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Attach binaries to release (Ubuntu)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./binary-ubuntu-latest/AppleTVRestarter-ubuntu-latest
        asset_name: AppleTVRestarter-ubuntu-latest-amd64
        asset_content_type: application/octet-stream

    - name: Attach binaries to release (macOS)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./binary-macos-latest/AppleTVRestarter-macos-latest
        asset_name: AppleTVRestarter-macos-latest-amd64
        asset_content_type: application/octet-stream

    - name: Attach binaries to release (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./binary-windows-latest/AppleTVRestarter-windows-latest
        asset_name: AppleTVRestarter-windows-latest-amd64
        asset_content_type: application/octet-stream
